Adicionado modelagem do banco de dados Resolve #11
marcosdosea/AgendeMe pull request #12
Opened 2022-08-11 21:20 UTC by lauro-ss

## Revisar
### - Relacionamentos
### - Indicies
### - Tipos

2022-08-12 12:28 UTC, ms-daniel requested changes
Solicito mudanças nos relacionamentos entre Agenda /Cidadão, Órgão Público/Cidadão e a relação entre Prefeitura/Órgão Público

2022-08-12 14:18 UTC, viniVN7 requested changes
Boa tarde. 
Por favor, verificar e realizar as seguintes modificações: 
- Os atributos "cep" e "numero" devem ser do tipo Varchar.
- Retirar o atributo "senha" da entidade "Cidadao"
- O atributo "sexo" deve ser do tipo Varchar.
- Definir os parâmetros corretos do atributo "tipoCidadao" no tipo enum.
- Verificar os locais onde há alguma chave estrangeira da tabela "Cidadao" e, definir o nome da chave de acordo com o tipo do cidadão relacionado a aquela tabela.
- Verificar a entidade "Agenda". Uma vez que, haverá um planejamento da agenda e a agenda em si.

2022-08-16 14:23 UTC, ms-daniel requested changes
Aguardar terminar diagramas de classe dos UC para finalizar o DER e posteriormente organizar o banco de dados.

2022-08-18 20:48 UTC, ms-daniel approved these changes
Tudo ok com o modelo do banco de dados e o DER.

2022-08-18 20:48 UTC, merged